### ISSUE TITLE
[meta] MV3 upstream issues

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditor#166]
* Gecko:
  * [ ] [1803950 - Dynamic import fails in content script in MV3 extension](https://bugzilla.mozilla.org/show_bug.cgi?id=1803950)
  * [ ] [1687778 - MV3 in-memory storage API (storage.session)](https://bugzilla.mozilla.org/show_bug.cgi?id=1687778)
* <del>Blink:
  * [ ] [1064671 - Service Worker-based extensions cannot load SVG image files. - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1064671)
     See also:
     * [1056354 - Allow some level of DOM parsing in service workers - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1056354)
     * [29683 - Extension icons should support SVG - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=29683)
     * [893175 - Light and Dark Mode Icons for Extensions - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=893175)
     * [Extension Icon Design for Light/Dark/Custom Theme on Browser Toolbar · Issue #229 · w3c/webextensions](https://github.com/w3c/webextensions/issues/229)
  </del>

**Comment by asamuzaK** [comment]
Ref [Chrome Extensions Manifest V2 support timeline - Chrome Developers](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)
Ref [Pausing Manifest V2 phase-out changes](https://groups.google.com/a/chromium.org/g/chromium-extensions/c/zQ77HkGmK9E)

**Comment by asamuzaK** [comment]
For a note: [1811443 - Support type: &quot;module&quot; (event page, not background service worker)](https://bugzilla.mozilla.org/show_bug.cgi?id=1811443)

**Comment by asamuzaK** [comment]
Ref [Manifest V2 support timeline | Extensions | Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline)

**Comment by asamuzaK** [comment]
Announcement:

This extension withExEditor is based on Firefox's WebExtensions and customized for Blink (i.e. Chrome and its variants).

Google has announced that support for MV2 extensions will end after June 2024.
Ref [Manifest V2 support timeline | Extensions | Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline)

I don't think the Firefox issues will be resolved anytime soon.

Unfortunately, withExEditor for Blink based browsers will likely be discontinued in June.

**Comment by asamuzaK** [comment]
See also [Changes to BFCache behavior with extension message ports | Blog | Chrome for Developers](https://developer.chrome.com/blog/bfcache-extension-messaging-changes)

**Comment by asamuzaK** [comment]
See also:
* [Longer extension service worker lifetimes | Blog | Chrome for Developers](https://developer.chrome.com/blog/longer-esw-lifetimes)
* [The extension service worker lifecycle | Extensions | Chrome for Developers](https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle)

**Comment by asamuzaK** [comment]
Support for Blink has already ended and there is no longer any reason to migrate to MV3.
Closing this issue as wontfix.
