### ISSUE TITLE
[meta] keyboard shortcuts features

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/withExEditor#82]
* [x] [1320462 - Add ability to set access key to context menu item](https://bugzilla.mozilla.org/show_bug.cgi?id=1320462 "1320462 - Add ability to set access key to context menu item")
* [ ] [1215061 - Better keyboard shortcut support](https://bugzilla.mozilla.org/show_bug.cgi?id=1215061 "1215061 - Better keyboard shortcut support")
* [x] [1303384 - UI for re-assigning an extension's command shortcut](https://bugzilla.mozilla.org/show_bug.cgi?id=1303384 "1303384 - UI for re-assigning an extension's command shortcut")
* [ ] [1320332 - Support overriding existing keybinding through WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1320332 "1320332 - Support overriding existing keybinding through WebExtensions")
